name: Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy Terraform resources'
        required: false
        default: 'false'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Change to Terraform directory
      run: cd infracraft/terraform
      working-directory: ./infracraft/terraform
        
    - name: Terraform Init
      run: terraform init
        
    - name: Terraform Plan
      run: terraform plan -out=plan.out
      
    - name: Terraform Apply
      if: ${{ github.event.inputs.destroy == 'false' }}
      run: terraform apply plan.out
      
    - name: Terraform Destroy
      if: ${{ github.event.inputs.destroy == 'true' }}
      run: terraform destroy -auto-approve
